<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Core abstractions and models for the FileTransfer library</Description>
    <PackageId>FileTransfer.Core</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.0" />
  </ItemGroup>

</Project>
