<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>SFTP provider for FileTransfer library</Description>
    <PackageId>FileTransfer.Providers.Sftp</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileTransfer.Core\FileTransfer.Core.csproj" />
    <ProjectReference Include="..\FileTransfer.Security\FileTransfer.Security.csproj" />
    <ProjectReference Include="..\FileTransfer.Compression\FileTransfer.Compression.csproj" />
    <ProjectReference Include="..\FileTransfer.Auditing\FileTransfer.Auditing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2024.1.0" />
  </ItemGroup>

</Project>
